title: sen × skutočnosť - Udalosti slovenského štátu v 4 kapitolách
metadata:
  description: "Jeden národ, jedna strana, jeden vodca, ale aj vyše 70 000 obetí – obdobie rokov 1939-1945 patrí medzi najkomplikovanejšie obdobia slovenských dejín."
  author: http://lab.sng.sk/
  keywords: sen x skutočnosť, umenie, propaganda, slovenského štátu, výstava, národ, Tiso, ríša, dream, reality, art, slovak state, exhibition, nation, empire
  url: http://senxskutocnost.sng.sk/

logo: /user/themes/longread/images/logo-sng.svg

date_long: 'd F Y'
date_short: 'd M Y'