title: sen × skutočnosť
description: Jeden národ, jedna strana, jeden vodca, ale aj vyše 70 000 obetí – obdobie rokov 1939-1945 patrí medzi najkomplikovanejšie obdobia slovenských dejín.
taxonomies: [tag, featured]
metadata:
    description: Jeden národ, jedna strana, jeden vodca, ale aj vyše 70 000 obetí – obdobie rokov 1939-1945 patrí medzi najkomplikovanejšie obdobia slovenských dejín.

logo: /user/themes/longread/images/logo-sng.svg

date_long: 'd F Y'
date_short: 'd M Y'

author:
    name: lab.SNG
    email: lab@sng.sk
    image: /user/images/avatar.jpg
    bio: I'm a blogger and a Grav-lover

social:
    - icon: twitter
      url: https://twitter.com/getgrav
      desc: Follow me on twitter
      share_url: http://twitter.com/share
      share_title: ?text=
      share_link: "&amp;url="

    - icon:  facebook
      url:   https://facebook.com/???
      desc: Connect with me facebook
      share_url: //www.facebook.com/sharer.php
      share_title: ?t=
      share_link: "&amp;u="

    - icon: github
      url: https://github.com/getgrav
      desc: Fork me on github
      share_url:
      share_title:
      share_link:

    - icon:  google-plus
      url:   https://google.com/???
      desc:  Add me on google+
      share_url:
      share_title:
      share_link:
