absolute_urls: true                        # Absolute or relative URLs for `base_url`

home:
  alias: '/chapters'

pages:
  theme: longread
  markdown:
    extra: true
  process:
    markdown: true
    twig: true

languages:
  supported:
    - sk
    - en
  override_locale: true
  include_default_lang: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
  enable_asset_timestamp: true             # Enable asset timestamps

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
